import { users } from "./users.js";

export const findUser = Object.fromEntries(
  users.map((user) => [user.id, user])
);

export let posts = [
  {
    id: 1,
    imgScr: "/images/posts/post_1.jpg",
    imgAlt: "Purple yarn sticking out of a woven handbag",
    title: "",
    caption: "Yay. finally got the new woven bag!",
    designer: "",
    pattern: "",
    yarn: "LilleRille Design",
    likes: "234",
    tag: "yarn",
    username: findUser[1].username,
    userId: 1,
    createdAt: "2025-03-19T12:00:00Z",
    commments: [
      {
        id: "cd1",
        text: "Great Bag for knitting",
        likes: 12,
        username: "StitchGoddess",
        userId: 4,
      },

      {
        id: "cd2",
        text: "Love the bag!",
        likes: 5,
        username: "YarnViking",
        userId: 3,
      },
    ],
  },

  {
    id: 2,
    imgScr: "/images/posts/post_2.jpg",
    imgAlt: "the neckline of an unfinished trouser for a child",
    title: "Finnaly started!",
    caption:
      "Finnly managed to start the roject for a set of nursery trouser for Willy",
    designer: "Havre",
    pattern: "Honingblomst bukser",
    yarn: "Sunday",
    likes: "432",
    tag: "wip",
    username: findUser[5].username,
    userId: 5,
    createdAt: "2025-03-19T12:03:23Z",
    commments: 0,
  },

  {
    id: 3,
    imgScr: "/images/posts/post_3.jpg",
    imgAlt: "A set of finsihed mittens",
    title: "New mittens!",
    caption: "A new pair for the comming winter",
    designer: "Sofie",
    pattern: "Kransevotter",
    yarn: "Mitu",
    likes: "245",
    tag: "finished",
    username: findUser[6].username,
    userId: 6,
    createdAt: "2025-03-09T12:00:00Z",
    commments: {},
  },

  {
    id: 4,
    imgScr: "/images/posts/post_4.jpg",
    imgAlt: "Dark pruple yarn lying on the floor",
    title: "",
    caption: "Treated myself to some new yarn!",
    designer: "",
    pattern: "",
    yarn: "LilleRille Design",
    likes: "354",
    tag: "yarn",
    username: findUser[1].username,
    userId: 1,
    createdAt: "2025-03-14T12:00:00Z",
    commments: [
      {
        id: "cd1",
        text: "Such a fantastic colour!",
        likes: 25,
        username: "YarnViking",
        userId: 3,
      },

      {
        id: "cd2",
        text: "Love the colour!",
        likes: 78,
        username: "KnotEnchanted",
        userId: 6,
      },
    ],
  },

  {
    id: 5,
    imgScr: "/images/posts/post_5.jpg",
    imgAlt: "A blue cardig with silver bling buttons",
    title: "New cardi",
    caption: "Finished this just in time for the wedding!",
    designer: "PetiteKnit",
    pattern: "Ballong Cardigan",
    yarn: "Merino",
    likes: "789",
    tag: "finsihed",
    username: findUser[5].username,
    userId: 5,
    createdAt: "2025-03-17T12:00:00Z",
    commments: 0,
  },

  {
    id: 6,
    imgScr: "/images/posts/post_6.jpg",
    imgAlt: "Orange yarn lying on a floor",
    title: "New socks!",
    caption: "Kniiting some new sock in prep for winter",
    designer: "Penelope",
    pattern: "Everyday socks",
    yarn: "Arwetta",
    likes: "584",
    tag: "wip",
    username: findUser[3].username,
    userId: 3,
    createdAt: "2025-03-17T12:00:28Z",
    commments: 0,
  },

  {
    id: 7,
    imgScr: "/images/posts/post_7.jpg",
    imgAlt: "A sweater in the making, just the yoke is finished",
    title: "Yoking away",
    caption: "Almost at separating the sleeves for this sweater!",
    designer: "BoylandKnitworks",
    pattern: "Winter",
    yarn: "Handmade",
    likes: "984",
    tag: "wip",
    username: findUser[4].username,
    userId: 4,
    createdAt: "2025-03-30T12:00:00Z",
    commments: 0,
  },

  {
    id: 8,
    imgScr: "/images/posts/post_8.jpg",
    imgAlt: "A green striped mohair cardigan",
    title: "New Cardi, who dis?",
    caption: "Finilay the Summer CCardi is done!!",
    designer: "AiryKnits",
    pattern: "Summer Cardi",
    yarn: "Tilia",
    likes: "1087",
    tag: "finished",
    username: findUser[4].username,
    userId: 4,
    createdAt: "2025-03-27T12:00:00Z",
    commments: 0,
  },

  {
    id: 9,
    imgScr: "/images/posts/post_14.jpg",
    imgAlt: "two bear balaclavas for children.",
    title: "",
    caption: "Knitted some new winter hats for my nephews",
    designer: "Knitting for Olive",
    pattern: "Bear Balaclava",
    yarn: "Merino",
    likes: 847,
    tag: "finsihed",
    username: findUser[2].username,
    userId: 2,
    createdAt: "2025-03-31T12:00:00Z",
    commments: [
      {
        id: "cd1",
        text: "They are soo cute!!",
        likes: 47,
        username: "LoopQueen",
        userId: 5,
      },
    ],
  },

  {
    id: 10,
    imgScr: "/images/posts/post_15.jpg",
    imgAlt: "neckline of a green cardigan",
    title: "Started a new summer project",
    caption: "",
    designer: "AiryKnits",
    pattern: "Summer Cardi",
    yarn: "Tilia",
    likes: "125",
    tag: "wip",
    username: findUser[4].username,
    userId: 4,
    createdAt: "2025-03-31T12:10:00Z",
    commments: [
      {
        id: "cd1",
        text: "Lovely colour!",
        likes: 6,
        username: "StichGodess",
        userId: 4,
      },
    ],
  },
];

console.log(posts);
